development:
  :address: smtp.gmail.com
  :port: 587
  :domain: teatercamp.no
  :authentication: plain
  :user_name: info@teatercamp.no
  :password: lekmedmeg
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: teatercamp.no
  :authentication: plain
  :user_name: info@teatercamp.no
  :password: lekmedmeg
  :enable_starttls_auto: true
  
